[IMP] docker-alpine-samba-dc: Break build args into dot env
LasLabs/docker-alpine-samba-dc pull request #4
Opened 2017-05-03 00:16 UTC by tedsalmon

* Move all the build args out of Dockerfile and into dot env
* Move AD DC initialization into entry point

FYI, the `mkdir` prior to the initial provisioning of the domain exists because any volume mounted post-image creation is going to be empty.

2017-05-03 00:17 UTC, lasley commented
Depends on LasLabs/docker-quality-tools#10

2017-05-03 00:40 UTC, tedsalmon commented
Alright, build is 🍏

2017-05-03 00:45 UTC, lasley requested changes
What about the ReadMe? You should also add usage sample(s)

2017-05-03 20:05 UTC, tedsalmon commented
Updated, @lasley!

2017-05-03 20:09 UTC, lasley requested changes

2017-05-03 20:09 UTC, lasley commented on README.md
> +     'samba-dc:1.0'
`laslabs/alpine-samba-dc:latest`

2017-05-03 20:09 UTC, lasley commented on README.md
> +After building the image, you should start it with the correct environment
There's no reason to build. Simply `docker pull laslabs/alpine-samba-dc:latest`

2017-05-03 20:09 UTC, lasley commented on README.md
> +After it's configured, you can run the container like so:
Maybe "After the container has been run the first time" or something?

2017-05-03 20:09 UTC, lasley commented on README.md
> +docker run --rm -i -t -v ${PWD}/samba:/samba 'samba-dc:1.0'
Why `--rm`?

2017-05-03 20:09 UTC, lasley commented on README.md
> +docker run --rm -i -t \
Why `--rm`? Also, why interactive? Isn't this a Daemon?

2017-05-03 20:09 UTC, lasley commented on docker-entrypoint.sh
> +    mkdir -p /samba/etc /samba/lib /samba/log
`echo "${SAMBA_DC_DOMAIN} - Begin Provisioning"`

2017-05-03 20:09 UTC, lasley commented on docker-entrypoint.sh
> +fi
`echo "${SAMBA_DC_DOMAIN} - Provisioned Successfully"`

2017-05-03 20:11 UTC, lasley commented on README.md
> +docker run --rm -i -t \
Maybe also `--restart unless-stopped`

2017-05-03 22:00 UTC, tedsalmon commented
Updated -- The Docker commands were a carryover of what I was using to test locally, derp. When you approve, I'll squash and merge.

Thanks!

2017-05-04 17:08 UTC, lasley commented on README.md
> +Now, start the image with the correct environmentvariables for initial
s/environmentvariables/environment variables

2017-05-05 00:07 UTC, tedsalmon commented on README.md
> +Now, start the image with the correct environmentvariables for initial
Odd -- Fixed! :)

2017-05-05 01:44 UTC, lasley approved these changes

2017-05-05 01:44 UTC, merged